// const items = [
//   {
//     img: imgSrc1,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc2,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc3,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc4,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc5,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc6,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc7,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc8,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc1,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc2,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc3,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc4,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc5,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc6,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc7,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
//   {
//     img: imgSrc8,
//     type: 'PostMainPage',
//     title: 'Title',
//     author: 'Vladimir',
//     reactions: {
//       emoji: 'some emoji',
//       emojiCount: 5,
//       likesCount: 200,
//     },
//   },
// ];
